### ISSUE TITLE
Does this "shell out"

### ISSUE THREAD

**Issue by azcromntic** [xemlock/php-latex#11]
### Description

Wasn't sure where to ask this question.  I don't use this site normally.  Anyway...does the php-latex shell out to the operating system to parse or "compile"?

**Comment by xemlock** [comment]
Hi @azcromntic,
Shell execution is used only when dealing with `pdflatex` binary, e.g., when calling `PhpLatex_PdfLatex::compile()`.

Parsing strings and files containing LaTeX markup, reformatting them into well-formed LaTeX, or rendering them to HTML is handled entirely by the library itself, without relying on external tools.
