### ISSUE TITLE
Unable to locate pdflatex binary

### ISSUE THREAD

**Issue by thethunderturner** [xemlock/php-latex#12]
### Description

I get this error after:
```php
    protected function generateAndDownloadPDF(string $content): void
    {
        $pdflatex = new PhpLatex_PdfLatex;
        $pathToGeneratedPdf = $pdflatex->compile('public/test.tex');
    }
```

Am I supposed to download something else?

### Additional Context

This code is from a laravel plugin that Im building

**Comment by xemlock** [comment]
Hi @thethunderturner!

Depending on the php configuration on the server, `pdflatex` binary may not be locatable (e.g. when `open_basedir` is in effect), while still being available for execution.

In such cases you need to explicitly provide `pdflatex` location, by calling:
```php
$pdflatex->setPdfLatexBinary('/path/to/pdflatex');
```
prior to running `compile()`.

**Comment by thethunderturner** [comment]
Thank you for your help!! :)
