### ISSUE TITLE
any example?

### ISSUE THREAD

**Issue by wuyidebh** [xemlock/php-latex#7]
Hi,
Is there any example?

**Comment by xemlock** [comment]
Hi @wuyidebh,
Basic usage is described in [README](https://github.com/xemlock/php-latex/blob/master/README.md), you may also find usage examples in [unit tests](https://github.com/xemlock/php-latex/blob/master/tests/PhpLatex/Test/).

**Comment by wuyidebh** [comment]
您好，已收到您的邮件，尽快给您回复。
